{
 "title": "Action Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Alloc Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"192.168.1.3:8989\"}"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"192.168.1.3:8888\"}"
    }
   ]
  },
  {
   "title": "Heap Alloc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"192.168.1.3:8989\"}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"192.168.1.3:8888\"}"
    }
   ]
  },
  {
   "title": "EPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(events_total{instance=\"192.168.1.3:8989\"}[$interval]))",
     "legendFormat": "transmitted by event generator"
    },
    {
     "expr": "sum(rate(events_total{instance=\"192.168.1.3:8888\"}[$interval]))",
     "legendFormat": "sent to clients"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "users_online{instance=\"192.168.1.3:8888\"}",
     "legendFormat": "Users"
    }
   ]
  }
 ]
}